version: '3'
services:

  ngrok-mediator-http:
    image: wernight/ngrok
    command: ngrok http mediator:3007 --log stdout
    networks:
      - app-network

  ngrok-mediator-ws:
    image: wernight/ngrok
    command: ngrok http mediator:3008 --log stdout
    networks:
      - app-network

  mediator:
    image: indicio-tech/aries-mediator
    hostname: mediator
    restart: unless-stopped
    environment:
      - NGROK_HTTP=ngrok-mediator-http
      - NGROK_WS=ngrok-mediator-ws
      - DEPLOYMENT_ENV=TEST
      - AGENT_NAME=mediator-test
      - WALLET_NAME=test-1
      - HTTP_ENDPOINT=http://localhost:3007
      - WS_ENDPOINT=ws://localhost:3008
      - HTTP_PORT=3007
      - WS_PORT=3008
      - RDBMS_URL=db:5432
      - RDBMS_AUTH={"account":"development","password":"development","admin_account":"development","admin_password":"development"}
    volumes:
      - ./ngrok-wait-http.sh:/home/indy/ngrok-wait-http.sh
      - ./ngrok-wait-ws.sh:/home/indy/ngrok-wait-ws.sh
    command: >
      sh -c "./ngrok-wait-http.sh ./ngrok-wait-ws.sh ./startup"
    ports: 
      - "3007:3007"
      - "3008:3008"
    depends_on:
      - "db"
    networks:
      - app-network

  # DB Service
  db:
    image: postgres:9.5
    hostname: db
    restart: always
    ports: # Uncomment to access postgres outside of containers
      - "5432:5432"
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge


