version: '3'
services:
  ngrok:
    image: wernight/ngrok
    environment:
      - MEDIATOR_AGENT_HTTP_IN_PORT=${MEDIATOR_AGENT_HTTP_IN_PORT:-3000}
    networks:
      - mediator-network
    command: ngrok http mediator:${MEDIATOR_AGENT_HTTP_IN_PORT:-3000} --log stdout

  ngrok_ws:
    image: wernight/ngrok
    environment:
      - MEDIATOR_AGENT_WS_IN_PORT=${MEDIATOR_AGENT_WS_IN_PORT:-3001}
    networks:
      - mediator-network
    command: ngrok http mediator:${MEDIATOR_AGENT_WS_IN_PORT:-3001} --log stdout

  tunnel:
    image: dbluhm/agent-tunnel
    networks:
      - mediator-network
    command: -s mediator:${MEDIATOR_AGENT_HTTP_IN_PORT:-3000} -p 4040 --host ${AGENT_TUNNEL_HOST}

  tunnel_ws:
    image: dbluhm/agent-tunnel
    networks:
      - mediator-network
    command: -s mediator:${MEDIATOR_AGENT_WS_IN_PORT:-3001} -p 4040 --host ${AGENT_TUNNEL_HOST}

  mediator-controller:
    image: node:fermium
    hostname: mediator-controller
    restart: unless-stopped
    environment:
      - PORT=${MEDIATOR_CONTROLLER_PORT:-3010}
      - CONTROLLER_ADMIN_API_KEY=${MEDIATOR_CONTROLLER_ADMIN_API_KEY}
      - MEDIATOR_ADMIN_URL=${MEDIATOR_AGENT_ADMIN_URL}
      - MEDIATOR_ADMIN_API_KEY=${MEDIATOR_AGENT_ADMIN_API_KEY}
      - MEDIATOR_ALIAS=${MEDIATOR_ALIAS}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./acapy/controller:/usr/src/controller
      - mediator-controller-data:/usr/src/controller/node_modules
    ports:
      - ${MEDIATOR_CONTROLLER_PORT:-3010}:${MEDIATOR_CONTROLLER_PORT:-3010}
    networks:
      - mediator-network
    working_dir: /usr/src/controller
    depends_on:
      - mediator
    entrypoint: /bin/bash
    command: ["-c", "npm install; npm run dev"]

  mediator:
    build:
      context: .
      dockerfile: acapy/Dockerfile.acapy
    hostname: mediator
    restart: unless-stopped
    environment:
      - ENV=${ENV:-local}
      - POSTGRESQL_HOST=${POSTGRESQL_HOST:-db}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT:-5432}
      - ACAPY_WALLET_STORAGE_CONFIG={"url":"${POSTGRESQL_HOST:-db}:${POSTGRESQL_PORT:-5432}","wallet_scheme":"DatabasePerWallet"}
      - ACAPY_WALLET_STORAGE_CREDS={"account":"${POSTGRESQL_USER:-postgres}","password":"${POSTGRESQL_PASSWORD:-development}","admin_account":"${POSTGRESQL_ADMIN_USER:-postgres}","admin_password":"${POSTGRESQL_ADMIN_PASSWORD:-development}"}
      - ACAPY_WALLET_NAME=${MEDIATOR_WALLET_NAME:-mediator}
      - ACAPY_WALLET_KEY=${MEDIATOR_WALLET_KEY:-testing}
      - MEDIATOR_AGENT_HTTP_IN_PORT=${MEDIATOR_AGENT_HTTP_IN_PORT:-3000}
      - MEDIATOR_AGENT_WS_IN_PORT=${MEDIATOR_AGENT_WS_IN_PORT:-3001}
      - MEDIATOR_AGENT_HTTP_ADMIN_PORT=${MEDIATOR_AGENT_HTTP_ADMIN_PORT:-3002}
      - MEDIATOR_AGENT_ADMIN_MODE=${MEDIATOR_AGENT_ADMIN_MODE:-admin-api-key 7gdmVBiJalMj52Oum50yD8neu/nxmv3/DTWcZPyKZ4K2UdNNwSPKgg==}
      - MEDIATOR_AGENT_LABEL=${MEDIATOR_AGENT_LABEL:-Mediator}
      - MEDIATOR_ENDPOINT_URL=${MEDIATOR_ENDPOINT_URL:-localhost}
      - MEDIATOR_ARG_FILE=${MEDIATOR_ARG_FILE:-./configs/mediator-auto-accept.yml}
      - MEDIATOR_CONTROLLER_WEBHOOK=${MEDIATOR_CONTROLLER_WEBHOOK}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    ports:
      - ${MEDIATOR_AGENT_HTTP_ADMIN_PORT:-3002}:${MEDIATOR_AGENT_HTTP_ADMIN_PORT:-3002}
      - ${MEDIATOR_AGENT_HTTP_IN_PORT:-3000}:${MEDIATOR_AGENT_HTTP_IN_PORT:-3000}
      - ${MEDIATOR_AGENT_WS_IN_PORT:-3001}:${MEDIATOR_AGENT_WS_IN_PORT:-3001}
    depends_on:
      - "db"
    networks:
      - mediator-network

  # DB Service
  db:
    image: postgres:10
    hostname: db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD:-development}
    ports: # Uncomment to access postgres outside of containers
      - "5432:5432"
    networks:
      - mediator-network
    volumes:
      - agency-wallet:/var/lib/pgsql/data

  # Nginx Service
  webserver:
    image: nginx:alpine
    build:
      context: nginx
      dockerfile: Dockerfile-nginx    
    hostname: webserver
    restart: unless-stopped
    environment:
      SSL_DOMAIN_PATH: ${SSL_DOMAIN_PATH}
      MEDIATOR_AGENT_HTTP_ADMIN_PORT: ${MEDIATOR_AGENT_HTTP_ADMIN_PORT:-3002}
      MEDIATOR_AGENT_HTTP_IN_PORT: ${MEDIATOR_AGENT_HTTP_IN_PORT:-3000}
      MEDIATOR_AGENT_WS_IN_PORT: ${MEDIATOR_AGENT_WS_IN_PORT:-3001} 
      NGINX_AGENT_HTTP_IN_PORT: ${NGINX_AGENT_HTTP_IN_PORT:-4000}
      NGINX_AGENT_WS_IN_PORT: ${NGINX_AGENT_WS_IN_PORT:-4001}    
      NGINX_HTTP_ADMIN_PORT: ${NGINX_HTTP_ADMIN_PORT:-4002}
    tty: true
    ports:
      - ${NGINX_AGENT_HTTP_IN_PORT:-4000}:${NGINX_AGENT_HTTP_IN_PORT:-4000}
      - ${NGINX_AGENT_WS_IN_PORT:-4001}:${NGINX_AGENT_WS_IN_PORT:-4001}    
      - ${NGINX_HTTP_ADMIN_PORT:-4002}:${NGINX_HTTP_ADMIN_PORT:-4002}      
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:consistent
      - ./nginx/conf.d/:/etc/nginx/templates/
      - ./nginx/docker-entrypoint.d/create-self-signed.sh:/docker-entrypoint.d/10-create-self-signed.sh
      - ./nginx/certbot-path:/certbot-path
    depends_on:
      - "mediator"
    networks:
      - mediator-network


#Docker Networks
networks:
  mediator-network:

volumes:
  agency-wallet:
  mediator-controller-data:
