version: '3'
services:
  ngrok:
    image: wernight/ngrok
    environment:
      - MEDIATOR_AGENT_HTTP_IN_PORT=${MEDIATOR_AGENT_HTTP_IN_PORT}
    networks:
      - mediator-network
    command: ngrok http mediator:${MEDIATOR_AGENT_HTTP_IN_PORT} --log stdout

  mediator:
    build:
      context: .
      dockerfile: acapy/Dockerfile.acapy
    hostname: mediator
    restart: unless-stopped
    environment:
      - ENV=${ENV:-local}
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - ACAPY_WALLET_STORAGE_CONFIG={"url":"${POSTGRESQL_HOST}:${POSTGRESQL_PORT}","wallet_scheme":"DatabasePerWallet"}
      - ACAPY_WALLET_STORAGE_CREDS={"account":"${POSTGRESQL_USER}","password":"${POSTGRESQL_PASSWORD}","admin_account":"${POSTGRESQL_ADMIN_USER}","admin_password":"${POSTGRESQL_ADMIN_PASSWORD}"}
      - ACAPY_WALLET_NAME=${MEDIATOR_WALLET_NAME}
      - ACAPY_WALLET_KEY=${MEDIATOR_WALLET_KEY}
      - MEDIATOR_AGENT_HTTP_IN_PORT=${MEDIATOR_AGENT_HTTP_IN_PORT}
      - MEDIATOR_AGENT_HTTP_ADMIN_PORT=${MEDIATOR_AGENT_HTTP_ADMIN_PORT}
      - MEDIATOR_AGENT_ADMIN_MODE=${MEDIATOR_AGENT_ADMIN_MODE}
      - MEDIATOR_AGENT_LABEL=${MEDIATOR_AGENT_LABEL}
    ports:
      - ${MEDIATOR_AGENT_HTTP_ADMIN_PORT}:${MEDIATOR_AGENT_HTTP_ADMIN_PORT}
      - ${MEDIATOR_AGENT_HTTP_IN_PORT}:${MEDIATOR_AGENT_HTTP_IN_PORT}
    depends_on:
      - "db"
    networks:
      - mediator-network

  # DB Service
  db:
    image: registry.access.redhat.com/rhscl/postgresql-95-rhel7:9.5
    hostname: db
    restart: always
#    ports: # Uncomment to access postgres outside of containers
#      - "5432:5432"
    environment:
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      POSTGRESQL_ADMIN_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD}
    networks:
      - mediator-network

#Docker Networks
networks:
  mediator-network:
